source 'https://cdn.cocoapods.org/'
use_frameworks!

def shared_pod
  pod 'JustTweak', :path => '../'
  script_phase :name => 'TweakAccessorGenerator',
               :script => '$SRCROOT/../JustTweak/Assets/TweakAccessorGenerator.bundle/TweakAccessorGenerator \
               -l $SRCROOT/JustTweak/TweakProviders/LocalTweaks_example.json \
               -o $SRCROOT/JustTweak/Accessors/ \
               -c $SRCROOT/JustTweak/CodeGeneration/',
               :execution_position => :before_compile
end

target 'JustTweakExample (iOS)' do
  platform :ios, '15.0'
  shared_pod

  target 'JustTweak_Tests' do
    inherit! :search_paths
  end
end

target 'JustTweakExample (macOS)' do
  platform :osx, '12.0'
  shared_pod
end

target 'JustTweakExample (tvOS)' do
  platform :tvos, '15.0'
  shared_pod
end
